name: Backup to FTP

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "ftp_host=${FTP_HOST}" >> $GITHUB_ENV
          echo "ftp_username=${FTP_USERNAME}" >> $GITHUB_ENV
          echo "ftp_password=${FTP_PASSWORD}" >> $GITHUB_ENV

      - name: Backup files to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ env.FTP_HOST }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local_path: ./
          remote_path: /mywebsitefillbackup/
          upload: true
          delete: false
