name: FTP Deploy to GitHub Pages

on: [push]

push:

branches:

- main

jobs:

deploy:

runs-on: ubuntu-latest

steps:

- name: Checkout code

uses: actions/checkout@v2

- name: Install GitFTP run: |

pip install git-ftp

name: Configure GitFTP

run: |

git config git-ftp.username $ {{ secrets.FTP_USERNAME }}

git config git-ftp.password $ {{ secrets.FTP_PASSWORD }}

git config git-ftp.host github.com

git config git-ftp.repo ${{ github.repository }}

git config git-ftp.branch gh-pages

name: Upload to GitHub Pages run: |

git ftp upload

- name: Deploy to GitHub Pages

uses: peaceiris/actions-gh-pages@v3 with:

github_token: ${{ secrets.GITHUB_TOKEN }}

publish_dir: ./public
